language: node_js
sudo: false

os:
  - linux
#  - osx

node_js:
  - '6.10.0'

cache:
  yarn: true
  directories:
    - node_modules

before_script:
  - yarn run build

script:
  - yarn run test

after_script:
  - yarn run coverage
