language: node_js
sudo: true

os:
  - linux
#  - osx

node_js:
  - '6.10.0'

cache:
  yarn: true
  directories:
    - node_modules

before_script:
#  - npm install -g yarn
  - apt-get install git
  - yarn

script:
  - yarn run test

after_script:
  - yarn run coverage